name: linuxdo_reader
description: 简单的 LinuxDo 首页帖子阅读器（Flutter）
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_widget_from_html_core: ^0.14.11
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.0.0
  photo_view: ^0.14.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
